# Getting Started: Python Fundamentals
## Practice Problems

###1. Start by loading the `subway_stations.csv` to a DataFrame, and then:

1.   Check the first 5 rows of subway_stations.
2.   Check subway_stations column data types and shape.
3.   How many unique values are in the station column?
4.   merge() the subway station data into delays_w_reasons (derived in class). Make sure that all delay records are kept, even if there is no matching station name in subway_stations. The resulting DataFrame should have 16,370 rows.

In [ ]:
import numpy as np
import pandas as pd

subway = pd.read_csv('/content/data/subway_stations.csv')
subway.head()

    stop_lat   stop_lon            station
0  43.666061 -79.411065   BATHURST STATION
1  43.670149 -79.390089        BAY STATION
2  43.766872 -79.386703    BAYVIEW STATION
3  43.769202 -79.376312  BESSARION STATION
4  43.670049 -79.385389      BLOOR STATION

In [ ]:
subway.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   stop_lat  77 non-null     float64
 1   stop_lon  77 non-null     float64
 2   station   77 non-null     object
dtypes: float64(2), object(1)
memory usage: 1.9+ KB

In [ ]:
len(subway['station'].unique())

77

In [ ]:
delay_w_reasons = pd.read_excel('/content/data/delays_w_reasons.xlsx')
merged = pd.merge(delay_w_reasons, 
                            subway, 
                            how='left',
                            left_on='station', 
                            right_on='station')
merged.head()

,date,time,day,station,code,min_delay,min_gap,bound,line,vehicle,code_description,stop_lat,stop_lon
0,2021-01-01,00:33,Friday,BLOOR STATION,MUPAA,0,0,N,YU,6046,Passenger Assistance Alarm Activated - No Trou...,43.670049,-79.385389
1,2021-01-01,00:39,Friday,SHERBOURNE STATION,EUCO,5,9,E,BD,5250,Couplers,43.672103,-79.376162
2,2021-01-01,01:07,Friday,KENNEDY BD STATION,EUCD,5,9,E,BD,5249,Consequential Delay (2nd Delay Same Fault),NaN,NaN
3,2021-01-01,01:41,Friday,ST CLAIR STATION,MUIS,0,0,NaN,YU,0,Injured or ill Customer (In Station) - Transpo...,43.687857,-79.391958
4,2021-01-01,02:04,Friday,SHEPPARD WEST STATION,MUIS,0,0,NaN,YU,0,Injured or ill Customer (In Station) - Transpo...,43.749571,-79.462186